# General Info
name: Bright Pixels
url: https://brightpixels.blog
description: A web-column about comic books, Star Wars, movies, Apple, technology, and other geekery.
timezone: America/Chicago
permalink: /:year/:month/:title/
exclude:
  ['README.md', 'Rakefile', 'vendor', 'Gemfile.lock', '.asset-cache', 'bin']
livereload: true
# Syntax Highlighting
highlighter: rouge

# Server
port: 4000

# Assets
sass:
  sass_dir: assets/stylesheets
  style: :compressed

# Markdown Rendering
markdown: kramdown
markdown_ext: markdown,mkdown,mkdn,mkd,md,mdown
kramdown:
  input: GFM

# Gems
plugins:
  - jekyll-typogrify

# Defaults
defaults:
  - scope:
      path: ''
      type: posts
    values:
      custom_type: link
      subtitle:
      excerpt:
      layout: post
      author: timsmith
      seo_title:
      link_url:
      featured_image:
      is_rss_only:
      review:
        type:
        rating:
        movie:
          letterboxd:

collections:
  uploads:
    title: Uploads
    output: true

# Social
social:
  links:
    - https://twitter.com/smithtimmytim
    - https://github.com/smithtimmytim
    - https://www.linkedin.com/in/smithtimmytim
    - https://www.flickr.com/photos/smithtimmytim
    - https://micro.blog/smith
    - https://twitter.com/brightpxblog

# Imgix
imgix:
  source: brightpixels.imgix.net
  secure_url_token: yecPTdx6GYCCJd7M

sizes: '(min-width: 90em) 1300px, (min-width: 70em) 1000px, (min-width: 50em) 750px, (min-width: 31.5em) 500px, 100vw'

srcset:
  - 500
  - 750
  - 1000
  - 1300
